=== Vfuentetaja/Examen_Recu_Ordinaria/Ejercicio_3/Untitled-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- elementos simles  asignatura-->
<xs:element name="nombre" type="xs:string"/>

<xs:element name="evaluacion">
    <xs:simpleType>
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="nota">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="suspenso"/>
            <xs:enumeration value="suficiente"/>
            <xs:enumeration value="notable"/>
            <xs:enumeration value="sobresaliente"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="telefono">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:pattern value="[1-9]{9}"/>
            </xs:restriction>
        </xs:simpleType>
</xs:element>

<!-- elemento compuesto asignatura-->

<xs:element name="asignatura" type="datos_asignatura"/>

    <xs:complexType name="datos_asignatura">
        <xs:sequence>
            <xs:element ref="nombre"/>
            <xs:element ref="evaluacion"/>
            <xs:element ref="nota" minOccurs="0" maxOccurs="9"/>
        </xs:sequence>
    </xs:complexType>

<!-- elemento compuesto alumno-->

    <xs:element name="alumnos" type="datos_alumnos"/>

    <xs:complexType name="datos_alumnos">
        <xs:sequence>
            <xs:element ref="nombre" minOccurs="1"/>
            <xs:element ref="telefono"/>
            <xs:element ref="asignatura"/>
        </xs:sequence>
    </xs:complexType>

<!-- elemento compuesto grupo-->
    <xs:element name="grupo" type="datos_grupo"/> 

    
    <xs:complexType name="datos_grupo">     
        <xs:sequence>
            <xs:element ref="nombre"/>
            <xs:element ref="alumnos" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

<!-- elemento compuesto nivel educativo-->

    <xs:element name="nivel_educativo" type="datos_nivel_educativo"/> 



    <xs:complexType name="datos_nivel_educativo">   
        <xs:sequence>
            <xs:element ref="nombre"/>
            <xs:element ref="grupo" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== Vfuentetaja/Examen_Recu_Ordinaria/Ejercicio_3/parte_xml_miguel_no_valido.xml
<?xml version="1.0" encoding="UTF-8"?>
<nivel_educativo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Untitled-2.xsd">
    <nombre>Bachillerato</nombre>
    <grupo>
        <nombre>2A</nombre>
        <alumnos>
            <nombre></nombre>
            <telefono></telefono>
            <asignatura>
                <nombre></nombre>
                <evaluacion></evaluacion>
                <nota></nota>
            </asignatura>
        </alumnos>
    </grupo>
</nivel_educativo>

=== Vfuentetaja/Examen_Recu_Ordinaria/Ejercicio_3/parte_xml_miguel.xml
<?xml version="1.0" encoding="UTF-8"?>
<nivel_educativo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Untitled-2.xsd">
    <nombre>Bachillerato</nombre>
    <grupo>
        <nombre>2ÂºA</nombre>
        <alumnos>
            <nombre>Marcos</nombre>
            <telefono>684375976</telefono>
            <asignatura>
                <nombre>Entornos</nombre>
                <evaluacion>1</evaluacion>
                <nota>notable</nota>
                <nota>suficiente</nota>
            </asignatura>
        </alumnos>
    </grupo>
</nivel_educativo>
